### ISSUE TITLE
Documentation - Clarify what is needed/wanted/desired

### ISSUE THREAD

**Issue by ruebot** [Islandora-CLAW/CLAW#51]
Looking at the [existing documentation](http://islandora-labs.github.io/islandora/), and pulling on discussions from the last couple Fedora 4 IG calls, I'd like to clarify what exactly folks are looking for documentation-wise. Currently we have documentation for:

* [About](http://islandora-labs.github.io/islandora/)
* Technical documenation
  * [Architecture](http://islandora-labs.github.io/islandora/technical-documentation/architecture/)
  * [Middleware Services](http://islandora-labs.github.io/islandora/technical-documentation/services/)
  * [Islandora Commands](http://islandora-labs.github.io/islandora/technical-documentation/commands/)
  * [How to build documentation](http://islandora-labs.github.io/islandora/technical-documentation/docs-build/)
* Contributing
  * [How to contribute](http://islandora-labs.github.io/islandora/contributing/contributing/)
  * [Hacking on Islandora](http://islandora-labs.github.io/islandora/contributing/hacking-on-islandora/)
* Migration
  * [Property mappings](http://islandora-labs.github.io/islandora/migration/migration/)
  * [fcrepo3 namespace predicates](http://islandora-labs.github.io/islandora/migration/fedora-namespace-predicates/)
  * [islandora namespace predicates](http://islandora-labs.github.io/islandora/migration/islandora-namespace-predicates/)
* [Vagrant](http://islandora-labs.github.io/islandora/install/README/)

@sprklinginfo @rosiel @dmoses would you mind articulating what else we could focus on documentation-wise? I can then pull that in a [task list](https://help.github.com/articles/writing-on-github/#task-lists) for this ticket, and we can collectively work on it during the sprint.

See the following "sub-issues" for this ticket:
  * [ ] #66 - Documentation - How To Create A Collection
  * [ ] #67 - Documentation - How To Ingest An Object
  * [ ] #68 - Documentation - How To Edit An Object's Medadata
  * [ ] #70 - Documentation - How To Purge (Delete?) An Object
  * [ ] #71 - Documentation - Islandora 2.x for Islandora 1.x Users
  * [ ] #72 - Documentation - How To Add An Object To A Collection
  * [ ] #74 - Documentation - How To Create A Collection View
  * [ ] #75 - Documentation - How To Edit An Ingest Form

**Comment by manez** [comment]
Not to speak for those folks, but I was thinking that a nice place to start for basic user docs would be to evaluate the "How To" pages we have in the current docs and see which ones still apply in the new stack, and then make them. "How to Edit an Object's Metadata, "How to Create a New Collection," etc.

https://wiki.duraspace.org/display/ISLANDORA/Getting+Started+with+Islandora

**Comment by sprklinginfo** [comment]
@ruebot: I just took a quick look at the latest vagrant copy. I tried to create a basic image collection first, then create two basic image objects. but the results seem kind of confusing. So from end user's point I would like to have a 'how-to' document about setting up a 'Basic Image Collection' with 1-2 basic images as members which conforms to PCDM model like the diagram described here: https://raw.githubusercontent.com/wiki/duraspace/pcdm/yEd/islandora-basic-image/Islandora-PCDM-Basic-Image.jpg. The end result should be a 'Basic Image Collection', which accessing the collection I can see other two images inside. Is it doable in current stage? From technical aspect, Is it possible to list all installation points/directories that technologies/components used in current islandora stack (vagrant). Tried to read those scripts or config under 'install' folder but lost somehow. I feel that it would be better to know how those technologies/components are pieced together according to http://islandora-labs.github.io/islandora/technical-documentation/architecture/

**Comment by sprklinginfo** [comment]
@ruebot when reading the 2015-09 Fedora Newsletter, it has mentioned "...But the highlight of the conference was the Fedora 4 and Islandora presentation by Nick Ruest (York University) and Danny Lamb (discoverygarden inc.) where they showcased a live demonstration of the Islandora/Fedora 4 prototype with a working basic image solution pack...". I think that is the 'how-to' document I meant in above comment.

**Comment by rosiel** [comment]
I think that the (promised, yet invisible) diagram of how the components fit together would be crucial.

I'd like some "Islandora 2.x for Islandora 1.x Users" guide that would map the things we're familiar with to the new version. e.g. 
* what's an object look like?
* does it have a pid?
* how are datastreams represented/attached?
* what about display?
* how are derivatives generated and where are they stored?

This could help with (my) more complex questions like:
* how do i create my own custom content model?
* how do i create my own variant of an existing content model?
etc. 

I'm hoping to brain-pick with @daniel-dgi next week and when I have answers to this could write up something.

**Comment by sprklinginfo** [comment]
@rosiel +1. The diagram is definitely needed with installation or deployed directories in current vagrant box. All other things you listed are what I wanted too. The display definitely is not the same as we have in 1.x. I already saw some issues but afraid it might be caused by the way I was creating objects not the correct workflow in 2.x, but I will report them later once I know what I should follow in 2.x.

**Comment by ruebot** [comment]
Closing this since it has been broken out into a number of issues.
